export default {
  ETHERSCAN_V1_MATCHES: [
    '*://zkevm.polygonscan.com/*',
    '*://optimistic.etherscan.io/*',
    '*://*.arbiscan.io/*',
    '*://testnet.ftmscan.com/*',
    '*://cronoscan.com/*',
    '*://*.basescan.org/*',
    '*://*.lineascan.build/*',
    '*://*.wemixscan.com/*',
    '*://gnosisscan.io/*',
    '*://*.celoscan.io/*',
    '*://*.bttcscan.com/*',
    '*://opbnb-testnet.bscscan.com/*',
    '*://optimistic.etherscan.io/*',
    '*://goerli-optimism.etherscan.io/*'
  ],
  ETHERSCAN_V2_MATCHES: [
    '*://ftmscan.com/*',
    '*://cn.etherscan.com/*',
    '*://goto.etherscan.com/*',
    '*://sepolia.etherscan.io/*',
    '*://goerli.etherscan.io/*',
    '*://cn.etherscan.com/*',
    '*://etherscan.io/*',
    '*://bscscan.com/*',
    '*://goto.bscscan.com/*',
    '*://www.bscscan.com/*',
    '*://testnet.bscscan.com/*',
    '*://polygonscan.com/*',
    '*://mumbai.polygonscan.com/*',
    '*://*.moonscan.io/*',
    '*://era.zksync.network/*'
  ],
  BTC_EXPLORER_MATCHES: ['*://explorer.btc.com/*'],
  BLOCKSEC_MATCHES: ['*://*.blocksec.com/*'],
  OPENSEA_MATCHES: ['*://*.opensea.io/*'],
  TRONSCAN_MATCHES: ['*://*.tronscan.org/*'],
  SNOWTRACE_MATCHES: ['*://*.snowtrace.io/*']
}
