export default {
  ETHERSCAN_V2_MATCHES: [
    '*://opbnb-testnet.bscscan.com/*',
    '*://ftmscan.com/*',
    '*://cn.etherscan.com/*',
    '*://goto.etherscan.com/*',
    '*://sepolia.etherscan.io/*',
    '*://goerli.etherscan.io/*',
    '*://cn.etherscan.com/*',
    '*://etherscan.io/*',
    '*://bscscan.com/*',
    '*://goto.bscscan.com/*',
    '*://www.bscscan.com/*',
    '*://testnet.bscscan.com/*',
    '*://polygonscan.com/*',
    '*://mumbai.polygonscan.com/*',
    '*://*.moonscan.io/*',
    '*://era.zksync.network/*',
    '*://snowscan.xyz/*',
    '*://optimistic.etherscan.io/*',
    '*://*.bttcscan.com/*',
    '*://*.celoscan.io/*',
    '*://zkevm.polygonscan.com/*',
    '*://*.lineascan.build/*',
    '*://*.wemixscan.com/*',
    '*://testnet.ftmscan.com/*',
    '*://*.basescan.org/*',
    '*://cronoscan.com/*',
    '*://gnosisscan.io/*',
    '*://*.arbiscan.io/*',
    '*://mantlescan.xyz/*',
    '*://sonicscan.org/*'
  ],
  BTC_EXPLORER_MATCHES: ['*://explorer.cloverpool.com/*'],
  BLOCKSEC_MATCHES: ['*://*.blocksec.com/*'],
  OPENSEA_MATCHES: ['*://*.opensea.io/*'],
  TRONSCAN_MATCHES: ['*://*.tronscan.org/*'],
  BLOCKSCOUT_MATCHES: ['*://*.blockscout.com/*'],
  MERLIN_SCAN_MATCHES: ['*://scan.merlinchain.io/*'],
  SOLSCAN_MATCHES: ['*://solscan.io/*'],
  SOLANAFM_MATCHES: ['*://solana.fm/*'],
  SOLANA_EXPLORER_MATCHES: ['*://explorer.solana.com/*'],
  MS_MATCHES: ['*://*.metasleuth.io/*'],
  DEBANK_MATCHES: ['*://debank.com/*'],
  ARKHAM_MATCHES: ['*://intel.arkm.com/*'],
  DEX_MATCHES: ['*://dexscreener.com/*'],
  JITO_MATCHES: ['*://explorer.jito.wtf/bundle/*']
}
