export const REFRESH = 'refresh'
export const GET_ADDRESS_RISK_SCORE = 'getAddressRiskScore'
export const GET_ADDRESS_LABEL = 'getAddressLabel'
export const GET_ADDRESS_METHOD = 'getAddressMethod'
export const GET_ADDRESS_FUND_FLOW = 'getAddressFundFlow'
export const EXECUTE_BTC_CONTENT_SCRIPT = 'executeBtcContentScript'
